name = "CCCE Modded"
author = "verdantfuture"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c4217ff181d9e62ec68d07ce5f74cf0641eb9636bd2c0a3f305ee346d9aade4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.93"
